version: "3"

services:
  scalaris1:
    networks:
      scalaris-network:
        ipv4_address: 10.0.10.11
    image: scalaris:latest
    container_name: scalaris1
    hostname: scalaris1
    environment:
      - CONSENSUS=mysticeti
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=debug,sui_network=debug,sui_node=debug,narwhal=debug,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
    volumes:
      - ./genesis/files/scalaris1-8080.yaml:/opt/scalaris/config/scalaris.yaml:ro
      - ./genesis/files/genesis.blob:/opt/scalaris/config/genesis.blob:ro
      - /tmp/scalaris/db1:/opt/scalaris/db:rw
    command: 
      [
        "/usr/local/bin/scalaris",
        "--config-path",
        "/opt/scalaris/config/scalaris.yaml",
      ]
    ports:
      - "8081:8080"
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
  scalaris2:
    networks:
      scalaris-network:
        ipv4_address: 10.0.10.12
    image: scalaris:latest
    container_name: scalaris2
    hostname: scalaris2
    environment:
      - CONSENSUS=mysticeti
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=debug,sui_network=debug,sui_node=debug,narwhal=debug,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
    volumes:
      - ./genesis/files/scalaris2-8080.yaml:/opt/scalaris/config/scalaris.yaml:ro
      - ./genesis/files/genesis.blob:/opt/scalaris/config/genesis.blob:ro
      - /tmp/scalaris/db2:/opt/scalaris/db:rw
    command:
      [
        "/usr/local/bin/scalaris",
        "--config-path",
        "/opt/scalaris/config/scalaris.yaml",
      ]
    ports:
      - "8082:8080"  
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
  scalaris3:
    networks:
      scalaris-network:
        ipv4_address: 10.0.10.13
    image: scalaris:latest
    container_name: scalaris3
    hostname: scalaris3
    environment:
      - CONSENSUS=mysticeti
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=debug,sui_network=debug,sui_node=debug,narwhal=debug,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
    volumes:
      - ./genesis/files/scalaris3-8080.yaml:/opt/scalaris/config/scalaris.yaml:ro
      - ./genesis/files/genesis.blob:/opt/scalaris/config/genesis.blob:ro
      - /tmp/scalaris/db3:/opt/scalaris/db:rw
    command: 
      [
        "/usr/local/bin/scalaris",
        "--config-path",
        "/opt/scalaris/config/scalaris.yaml",
      ]
    ports:
      - "8083:8080"  
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
  scalaris4:
    networks:
      scalaris-network:
        ipv4_address: 10.0.10.14
    image: scalaris:latest
    container_name: scalaris4
    hostname: scalaris4
    environment:
      - CONSENSUS=mysticeti
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=debug,sui_network=debug,sui_node=debug,narwhal=debug,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
    volumes:
      - ./genesis/files/scalaris4-8080.yaml:/opt/scalaris/config/scalaris.yaml:ro
      - ./genesis/files/genesis.blob:/opt/scalaris/config/genesis.blob:ro
      - /tmp/scalaris/db4:/opt/scalaris/db:rw
    command: 
      [
        "/usr/local/bin/scalaris",
        "--config-path",
        "/opt/scalaris/config/scalaris.yaml",
      ]
    ports:
      - "8084:8080"  
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
networks:
  scalaris-network:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.10.0/24
